<script setup lang="ts">
import { computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { analyticsApi } from '../api/analytics'
import { useAsyncState } from '../composables/useAsyncState'
import StatePanel from '../components/ui/StatePanel.vue'
const route=useRoute(),router=useRouter(),period=computed(()=>Number(route.query.period)||30),{data,loading,error,load}=useAsyncState(()=>analyticsApi.summary(period.value))
const sections=computed<Array<[string,Record<string,number|null>|undefined]>>(()=>data.value?[['Головная боль',data.value.pain],['Лекарства',data.value.medication],['Сон',data.value.sleep],['Активность',data.value.activity],['Самочувствие',data.value.wellbeing]]:[])
watch(period,()=>load());onMounted(()=>load())
</script>
<template><div class="page stack"><header><p class="eyebrow">Только подтверждённые данные</p><h1>Аналитика</h1></header><div class="segmented"><button v-for="days in [7,30,60,90]" :key="days" :class="{active:period===days}" @click="router.replace({query:{period:days}})">{{days}} дней</button></div><StatePanel v-if="loading" kind="loading"/><StatePanel v-else-if="error" kind="error" :message="error" @retry="load()"/><template v-else-if="data"><section class="card"><h2>Покрытие данных</h2><div class="metrics"><span><b>{{data.diary_days??0}}</b> дней с записями</span><span><b>{{data.confirmed_events??0}}</b> подтверждено</span><span><b>{{data.pending_events??0}}</b> ожидает</span><span><b>{{data.closed_episode_count??0}} / {{data.total_episode_count??0}}</b> завершённых эпизодов</span></div><p class="muted">Период: {{period}} дней · {{data.timezone||'часовой пояс профиля'}}</p></section><section v-for="[title,values] in sections" :key="title" class="card"><h2>{{title}}</h2><StatePanel v-if="!values||!Object.keys(values).length" kind="empty" title="Недостаточно данных" message="В этом периоде пока нет достаточного числа подтверждённых записей."/><dl v-else><template v-for="(value,key) in values" :key="key"><dt>{{String(key).replaceAll('_',' ')}}</dt><dd>{{value??'Не указано'}}</dd></template></dl></section><section v-if="data.associations?.length" class="card"><h2>Возможные связи</h2><article v-for="item in data.associations" :key="item.label"><strong>{{item.label}}</strong><p>{{item.description}} · выборка: {{item.sample_size}}</p></article></section><details class="card"><summary>Ограничения и формулы</summary><p>Версия формул: {{data.formula_version||'не указана'}}</p><ul><li v-for="item in data.limitations" :key="item">{{item}}</li></ul><p>Совпадение наблюдений не означает причинную связь.</p></details></template></div></template>
<style scoped>.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:var(--s4)}.metrics b{display:block;font-size:1.6rem;font-variant-numeric:tabular-nums}dl{display:grid;grid-template-columns:1fr auto;gap:var(--s2)}dd{margin:0;font-weight:700}</style>
