<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ApiError } from '../api/client'
import { journalApi } from '../api/journal'
import type { HealthEvent } from '../api/types'
import { descriptorFor } from '../features/events/eventRegistry'
import StatePanel from '../components/ui/StatePanel.vue'
import UiButton from '../components/ui/UiButton.vue'
const id=String(useRoute().params.id),event=ref<HealthEvent|null>(null),loading=ref(true),error=ref(''),saving=ref(false),conflict=ref(false),fields=reactive<Record<string,string>>({}),original=reactive<Record<string,string>>({}),validation=reactive<Record<string,string>>({})
const descriptor=computed(()=>descriptorFor(event.value?.kind||'note'))
async function load(){loading.value=true;error.value='';try{event.value=await journalApi.event(id);const data=event.value.data||event.value.attributes||{};Object.assign(fields,{occurred_at:event.value.occurred_at.slice(0,16),time_precision:event.value.time_precision||'exact'});for(const f of descriptor.value.fields)fields[f.key]=data[f.key]==null?'':String(data[f.key]);Object.assign(original,fields)}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function save(){if(!event.value)return;saving.value=true;conflict.value=false;Object.keys(validation).forEach(k=>delete validation[k]);const data:Record<string,unknown>={},patch:Record<string,unknown>={revision:event.value.revision};for(const [key,val] of Object.entries(fields)){if(val===original[key])continue;if(key==='occurred_at')patch.occurred_at=new Date(val).toISOString();else if(key==='time_precision')patch.time_precision=val;else data[key]=val===''?null:(['intensity','score','quality','duration_minutes','dose_value','value'].includes(key)?Number(val):val)}if(Object.keys(data).length)patch.data=data;try{event.value=await journalApi.update(id,patch);Object.assign(original,fields)}catch(e){if(e instanceof ApiError){Object.assign(validation,e.fields);conflict.value=e.isConflict}error.value=(e as Error).message}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="page"><StatePanel v-if="loading" kind="loading"/><StatePanel v-else-if="!event" kind="error" :message="error" @retry="load"/><form v-else class="card stack" @submit.prevent="save"><header><p class="eyebrow">Редактирование</p><h1>{{ descriptor.label }}</h1></header><p v-if="error&&!conflict" role="alert">{{error}}</p><div v-if="conflict" class="card" role="alert"><strong>Событие изменилось в другом месте.</strong><p>Ваш черновик сохранён в форме.</p><UiButton type="button" variant="secondary" @click="load">Загрузить актуальную версию</UiButton></div><label class="field">Дата и время<input v-model="fields.occurred_at" type="datetime-local"/><span class="field-error">{{validation.occurred_at}}</span></label><label class="field">Точность времени<select v-model="fields.time_precision"><option value="exact">Точное</option><option value="approximate">Примерное</option><option value="unknown">Не указано</option></select></label><label v-for="field in descriptor.fields" :key="field.key" class="field">{{field.label}}<input v-model="fields[field.key]" :type="['intensity','score','quality','duration_minutes','dose_value','value'].includes(field.key)?'number':'text'" :min="['intensity','score','quality'].includes(field.key)?0:undefined" :max="['intensity','score','quality'].includes(field.key)?10:undefined" :placeholder="'Не указано'"/><span class="field-error">{{validation[field.key]}}</span></label><div class="cluster"><UiButton :busy="saving">Сохранить</UiButton><RouterLink :to="`/day/${event.occurred_at.slice(0,10)}`">Отмена</RouterLink></div></form></div></template>
