<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { authApi } from '../api/auth'
import { settingsApi } from '../api/settings'
import { useSession } from '../composables/useSession'
import { useToast } from '../composables/useToast'
import UiButton from '../components/ui/UiButton.vue'
import UiDialog from '../components/ui/UiDialog.vue'
const session=useSession(),timezone=ref(session.user.value?.timezone||'Europe/Moscow'),dayStart=ref(session.user.value?.settings?.day_start_time||'00:00'),danger=ref(false),busy=ref(false),toast=useToast(),router=useRouter()
async function save(){busy.value=true;try{session.authenticated(await settingsApi.update({timezone:timezone.value,locale:'ru',settings:{day_start_time:dayStart.value}}));toast.show('Настройки сохранены')}catch(e){toast.show((e as Error).message)}finally{busy.value=false}}
async function logout(){await authApi.logout();session.expire('/today');router.push('/login')}
async function remove(){busy.value=true;try{await settingsApi.deleteAccount();session.expire();router.push('/login')}catch(e){toast.show((e as Error).message)}finally{busy.value=false}}
</script>
<template><div class="page stack"><header><p class="eyebrow">Профиль и данные</p><h1>Ещё</h1></header><section class="card stack"><h2>Профиль</h2><label class="field">Часовой пояс<input v-model="timezone" autocomplete="off"/></label><label class="field">Начало нового дня<input v-model="dayStart" type="time" step="60"/><small class="muted">События до этого времени относятся к предыдущему дню. По умолчанию — 00:00.</small></label><UiButton :busy="busy" @click="save">Сохранить</UiButton></section><section class="card"><h2>Приватность</h2><p>Исходные сообщения отделены от извлечённых фактов. Для распознавания используется внешний LLM-провайдер в описанных границах.</p><RouterLink to="/privacy">Подробнее о данных и хранении</RouterLink></section><section class="card"><h2>Экспорт</h2><p>Скачайте текущие подтверждённые данные. Ответ не кешируется приложением.</p><div class="cluster"><a class="button button--secondary" :href="settingsApi.exportUrl('json')">JSON</a><a class="button button--secondary" :href="settingsApi.exportUrl('csv')">CSV</a></div></section><section class="card"><h2>Сессии</h2><div class="cluster"><UiButton variant="secondary" @click="logout">Выйти</UiButton><UiButton variant="ghost" @click="authApi.logoutAll().then(logout)">Выйти на всех устройствах</UiButton></div></section><section class="card danger-zone"><h2>Опасная зона</h2><p>Удаление затрагивает исходные записи, события, ревизии, экспорты и сессии сервиса. История чата Telegram удаляется отдельно. Копии исчезают после окончания срока хранения резервных копий.</p><UiButton variant="danger" @click="danger=true">Удалить данные аккаунта</UiButton></section><UiDialog :open="danger" title="Удалить все данные?" @close="danger=false"><p>Операцию нельзя отменить. Сервер может запросить недавнюю повторную авторизацию.</p><div class="cluster"><UiButton variant="danger" :busy="busy" @click="remove">Удалить всё</UiButton><UiButton variant="secondary" @click="danger=false">Отмена</UiButton></div></UiDialog></div></template>
<style scoped>.danger-zone{margin-top:var(--s7);border-color:#e6b6b3}</style>
