stages: [check, build, publish]

check:
  stage: check
  image: golang:1.26
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    - apt-get install -y nodejs
  script:
    - make check

docker-build:
  stage: build
  image: docker:29
  services: [docker:29-dind]
  script:
    - docker build -t health-diary:$CI_COMMIT_SHA .

publish-image:
  stage: publish
  image: docker:29
  services: [docker:29-dind]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
