<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

type Event = { id:string; kind:string; occurred_at:string; attributes:Record<string, unknown>; revision:number; status?:string }
type Batch = { id:string; version:number; created_at:string; events:Event[] }
const me = ref<{id:string; timezone:string}|null>(null), code=ref(''), error=ref(''), challenge=ref<{id:string; telegramUrl?:string}|null>(null)
const events=ref<Event[]>([]), batches=ref<Batch[]>([]), month=ref(new Date().toISOString().slice(0,7)), loading=ref(false)
const fmt = new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'})
const eventLabel=(event:Event) => `${event.kind.replaceAll('_',' ')} · ${fmt.format(new Date(event.occurred_at))}`
const days=computed(() => { const grouped:Record<string,Event[]>={}; for (const e of events.value) { const d=e.occurred_at.slice(0,10); (grouped[d]??=[]).push(e) }; return Object.entries(grouped).sort(([a],[b])=>b.localeCompare(a)) })
async function api(path:string, init:RequestInit={}) { const r=await fetch(path,{...init,credentials:'same-origin',headers:{'Content-Type':'application/json',...(init.headers||{})}}); if(!r.ok) throw new Error(r.status===401?'Нужен новый вход.':'Операция не выполнена.'); return r.status===204?null:r.json() }
async function load() { loading.value=true; try { const [profile, list, pending]=await Promise.all([api('/api/me'),api('/events'),api('/batches/pending')]); me.value=profile; events.value=list.events; batches.value=pending.batches } catch { me.value=null } finally { loading.value=false } }
async function beginLogin() { error.value=''; try { const item=await api('/auth/challenges',{method:'POST'}); challenge.value={id:item.challenge_id,telegramUrl:item.telegram_url} } catch(e) { error.value=(e as Error).message } }
async function verify() { if(!challenge.value) return; try { await api(`/auth/challenges/${challenge.value.id}/verify`,{method:'POST',body:JSON.stringify({code:code.value})}); await load() } catch(e) { error.value=(e as Error).message } }
async function transitionBatch(id:string, version:number, action:'confirm'|'reject') { try { await api(`/batches/${id}/${action}`,{method:'POST',body:JSON.stringify({version})}); await load() } catch(e) { error.value=(e as Error).message } }
async function remove(event:Event) { if(!confirm('Удалить событие из дневника? Исходная запись сохраняется до отдельного удаления данных.')) return; try { await api(`/events/${event.id}?revision=${event.revision}`,{method:'DELETE'}); await load() } catch(e) { error.value=(e as Error).message } }
async function deleteAccount() { if(!confirm('Удалить все данные дневника без возможности восстановления в сервисе? Данные в резервных копиях исчезнут только по их сроку хранения.')) return; try { await api('/me/deletion-request',{method:'POST',body:JSON.stringify({confirm:'DELETE_MY_DATA'})}); me.value=null; error.value='Запрос на удаление принят. Текущая сессия завершена.' } catch(e) { error.value=(e as Error).message } }
onMounted(load)
</script>

<template>
  <main>
    <header><div><p class="eyebrow">Личный дневник</p><h1>Здоровье — без догадок</h1></div><span v-if="me" class="user">{{ me.timezone }}</span></header>
    <p v-if="error" class="error" role="alert">{{ error }}</p>
    <section v-if="!me" class="card login"><h2>Войти через Telegram</h2><p>Код одноразовый, действует несколько минут. Мы не показываем исходные записи в этом интерфейсе без отдельного действия.</p><button v-if="!challenge" @click="beginLogin">Получить код</button><template v-else><a v-if="challenge.telegramUrl" :href="challenge.telegramUrl">Открыть бота и получить код</a><p v-else>Откройте бота, отправьте <code>/start login_…</code> из ссылки входа.</p><label>Код из Telegram<input v-model="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" @keyup.enter="verify" /></label><button @click="verify">Войти</button></template></section>
    <template v-else><section v-if="batches.length" class="card"><h2>Ожидают подтверждения</h2><article v-for="batch in batches" :key="batch.id" class="batch"><ul><li v-for="event in batch.events" :key="event.id">{{ eventLabel(event) }}</li></ul><div><button @click="transitionBatch(batch.id,batch.version,'confirm')">Верно</button><button class="quiet" @click="transitionBatch(batch.id,batch.version,'reject')">Отклонить</button></div></article></section><section class="card"><div class="section-title"><h2>Подтверждённые события</h2><div><a href="/exports?format=json">JSON</a> · <a href="/exports?format=csv">CSV</a></div></div><p v-if="loading">Обновляем…</p><p v-else-if="!days.length">Пока нет подтверждённых событий. Отправьте запись боту — затем подтвердите факты здесь.</p><div v-for="[day, items] in days" :key="day" class="day"><h3>{{ day }}</h3><article v-for="event in items" :key="event.id"><div><strong>{{ eventLabel(event) }}</strong><pre v-if="Object.keys(event.attributes).length">{{ JSON.stringify(event.attributes, null, 2) }}</pre></div><button class="quiet danger" @click="remove(event)">Удалить</button></article></div></section><section class="card"><h2>Удаление аккаунта</h2><p>Удалит исходные записи, события и сессии из сервиса. Резервные копии удаляются по своему защищённому сроку хранения. Для защиты нужна повторная авторизация в течение 10 минут.</p><button class="quiet danger" @click="deleteAccount">Удалить все данные</button></section><p class="notice">Дневник не ставит диагнозы и не даёт медицинских рекомендаций. Неподтверждённые факты не попадают в обзор и экспорт.</p></template>
  </main>
</template>

<style>
:root{font-family:Inter,system-ui,sans-serif;color:#15221b;background:#f4f7f3}*{box-sizing:border-box}body{margin:0}main{max-width:780px;margin:auto;padding:28px 16px 72px}header,.section-title,.batch>div,.day article{display:flex;align-items:center;justify-content:space-between;gap:16px}h1{margin:2px 0;font-size:clamp(28px,6vw,42px)}h2{margin-top:0}.eyebrow{color:#447157;text-transform:uppercase;letter-spacing:.08em;font-size:12px;margin:0}.user,.notice{color:#526158;font-size:14px}.card{background:#fff;border:1px solid #dce5dc;border-radius:18px;padding:22px;margin-top:22px;box-shadow:0 3px 16px #13210b0b}.login{max-width:500px}.batch{border-top:1px solid #e5ece5;padding:14px 0}.batch ul{padding-left:20px;margin:0}.day{border-top:1px solid #e5ece5;padding:14px 0}.day h3{font-size:14px;color:#526158}.day article{padding:9px 0}button,a{font:inherit}button{border:0;border-radius:10px;background:#216640;color:white;padding:10px 14px;font-weight:650;cursor:pointer}.quiet{background:#e8efe9;color:#23402b}.danger{color:#8a2525}a{color:#216640;font-weight:650}label{display:grid;gap:6px;margin:14px 0}input{padding:12px;border:1px solid #aab9ad;border-radius:9px;font-size:18px;letter-spacing:.12em}pre{white-space:pre-wrap;font:12px ui-monospace,monospace;color:#526158;margin:7px 0}.error{background:#ffe8e7;color:#8a2525;padding:12px;border-radius:10px}@media(max-width:520px){.day article{align-items:flex-start}.day article button{padding:8px}.section-title{align-items:flex-start}}
</style>
